#  Intermediate Net in Keras

Building a intermediateneural netwok to classift MNIST digits

The images are 28 pixels by 28 pixels, total 784 pixels

#### Set seed for reproducibility

In [1]:
import numpy as np
np.random.seed(42)

In [23]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#### Load dependencies

In [24]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD #stochastic Gradient Descent

#### Load Data

In [25]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [26]:
X_train.shape
y_train.shape

(60000, 28, 28)

(60000,)

In [5]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [6]:
X_train[0]
# 0's represents white color, 255 is the darkest, black.

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [7]:
X_test.shape

(10000, 28, 28)

In [8]:
y_test.shape

(10000,)

#### Preprocess data

In [9]:
# 60000 images converted into 784*1 array and dataype converted into float32
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [10]:
## we normalize and make the highest value 1 instead of 255

X_train /= 255
X_test /= 255

In [11]:
X_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [12]:
## we convert y into one-hot encoded

n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [13]:
y_train[0] # represents 5

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

#### Design neural network architecture 

In [14]:
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(784,))) #input_shape is 784 by 1
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [15]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [16]:
# we cannot see the input layer above but we know that it has 784*1
# how to get the parameters, 784(input neurons) * 64(hidden layer neurons) + 64 = 50240 (64 is the hidden layer neuron number)
# 64 * 10 + 10 = 650
# fully-connected

#### Configure Model 

In [17]:
# model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#### Train

In [18]:
# model.fit(X_train, y_train, batch_size=128, epochs=1, verbose=1, validation_data=(X_test, y_test))

In [19]:
# as we can see this is almost random chance and we got barely 10% accuracy
# lets increase epeochs to 20

In [20]:
# model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_test, y_test))

In [21]:
# we get better results as we increase the epoch number
# if you do not restar the kernel training goes on from the preboius one so you should restar kernel if you 
# change epoch

In [22]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 20us/step - loss: 0.3842 - acc: 0.8935 - val_loss: 0.1882 - val_acc: 0.9472
Epoch 2/200
60000/60000 [==============================] - 1s 16us/step - loss: 0.1590 - acc: 0.9534 - val_loss: 0.1348 - val_acc: 0.9598
Epoch 3/200
60000/60000 [==============================] - 1s 16us/step - loss: 0.1178 - acc: 0.9645 - val_loss: 0.1215 - val_acc: 0.9645
Epoch 4/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0954 - acc: 0.9722 - val_loss: 0.1089 - val_acc: 0.9680
Epoch 5/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0791 - acc: 0.9764 - val_loss: 0.1004 - val_acc: 0.9695
Epoch 6/200
60000/60000 [==============================] - 1s 16us/step - loss: 0.0662 - acc: 0.9804 - val_loss: 0.0928 - val_acc: 0.9709
Epoch 7/200
60000/60000 [==============================] - 1s 14us/step - 

60000/60000 [==============================] - 1s 14us/step - loss: 0.0041 - acc: 0.9985 - val_loss: 0.1354 - val_acc: 0.9767
Epoch 58/200
60000/60000 [==============================] - 1s 14us/step - loss: 0.0019 - acc: 0.9994 - val_loss: 0.1314 - val_acc: 0.9772
Epoch 59/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0027 - acc: 0.9991 - val_loss: 0.1327 - val_acc: 0.9783
Epoch 60/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0044 - acc: 0.9985 - val_loss: 0.1622 - val_acc: 0.9731
Epoch 61/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0056 - acc: 0.9983 - val_loss: 0.1522 - val_acc: 0.9760
Epoch 62/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0058 - acc: 0.9980 - val_loss: 0.1381 - val_acc: 0.9775
Epoch 63/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0054 - acc: 0.9981 - val_loss: 0.1308 - val_acc: 0.9777
Epoch 64/200
60000/60000 [==============

Epoch 115/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.7719e-05 - acc: 1.0000 - val_loss: 0.1473 - val_acc: 0.9787
Epoch 116/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.5459e-05 - acc: 1.0000 - val_loss: 0.1477 - val_acc: 0.9789
Epoch 117/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.3518e-05 - acc: 1.0000 - val_loss: 0.1482 - val_acc: 0.9789
Epoch 118/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.1638e-05 - acc: 1.0000 - val_loss: 0.1486 - val_acc: 0.9790
Epoch 119/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.0005e-05 - acc: 1.0000 - val_loss: 0.1495 - val_acc: 0.9792
Epoch 120/200
60000/60000 [==============================] - 1s 15us/step - loss: 8.7159e-06 - acc: 1.0000 - val_loss: 0.1496 - val_acc: 0.9793
Epoch 121/200
60000/60000 [==============================] - 1s 15us/step - loss: 7.6966e-06 - acc: 1.0000 - val_loss: 0.1503 - val_acc:

Epoch 173/200
60000/60000 [==============================] - 1s 15us/step - loss: 3.3662e-06 - acc: 1.0000 - val_loss: 0.1590 - val_acc: 0.9798
Epoch 174/200
60000/60000 [==============================] - 1s 15us/step - loss: 2.9303e-06 - acc: 1.0000 - val_loss: 0.1593 - val_acc: 0.9801
Epoch 175/200
60000/60000 [==============================] - 1s 15us/step - loss: 2.5749e-06 - acc: 1.0000 - val_loss: 0.1592 - val_acc: 0.9802
Epoch 176/200
60000/60000 [==============================] - 1s 16us/step - loss: 2.2314e-06 - acc: 1.0000 - val_loss: 0.1599 - val_acc: 0.9801
Epoch 177/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.9544e-06 - acc: 1.0000 - val_loss: 0.1601 - val_acc: 0.9800
Epoch 178/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.6851e-06 - acc: 1.0000 - val_loss: 0.1607 - val_acc: 0.9800
Epoch 179/200
60000/60000 [==============================] - 1s 15us/step - loss: 1.4784e-06 - acc: 1.0000 - val_loss: 0.1609 - val_acc: