#  Shallow Net in Keras

Building a shallow neural netwok to classift MNIST digits

The images are 28 pixels by 28 pixels, total 784 pixels

#### Set seed for reproducibility

In [47]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [48]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD #stochastic Gradient Descent

#### Load Data

In [49]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [50]:
X_train.shape

(60000, 28, 28)

In [51]:
y_train.shape

(60000,)

In [52]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [53]:
X_train[0]
# 0's represents white color, 255 is the darkest, black.

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [54]:
X_test.shape

(10000, 28, 28)

In [55]:
y_test.shape

(10000,)

#### Preprocess data

In [56]:
# 60000 images converted into 784*1 array and dataype converted into float32
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [57]:
## we normalize and make the highest value 1 instead of 255

X_train /= 255
X_test /= 255

In [58]:
X_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [59]:
## we convert y into one-hot encoded

n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [60]:
y_train[0] # represents 5

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

#### Design neural network architecture 

In [61]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,))) #input_shape is 784 by 1
model.add(Dense(10, activation='softmax'))

In [62]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [63]:
# we cannot see the input layer above but we know that it has 784*1
# how to get the parameters, 784(input neurons) * 64(hidden layer neurons) + 64 = 50240 (64 is the hidden layer neuron number)
# 64 * 10 + 10 = 650
# fully-connected

#### Configure Model 

In [64]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train

In [43]:
model.fit(X_train, y_train, batch_size=128, epochs=1, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/1
60000/60000 [==============================] - 1s 12us/step - loss: 0.0908 - acc: 0.1076 - val_loss: 0.0907 - val_acc: 0.1135


In [44]:
# as we can see this is almost random chance and we got barely 10% accuracy
# lets increase epeochs to 20

In [65]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 1s 13us/step - loss: 0.0915 - acc: 0.0895 - val_loss: 0.0911 - val_acc: 0.0955
Epoch 2/20
60000/60000 [==============================] - 1s 11us/step - loss: 0.0908 - acc: 0.1058 - val_loss: 0.0905 - val_acc: 0.1162
Epoch 3/20
60000/60000 [==============================] - 1s 11us/step - loss: 0.0903 - acc: 0.1406 - val_loss: 0.0901 - val_acc: 0.1513
Epoch 4/20
60000/60000 [==============================] - 1s 11us/step - loss: 0.0899 - acc: 0.1925 - val_loss: 0.0897 - val_acc: 0.2058
Epoch 5/20
60000/60000 [==============================] - 1s 11us/step - loss: 0.0895 - acc: 0.2401 - val_loss: 0.0893 - val_acc: 0.2424
Epoch 6/20
60000/60000 [==============================] - 1s 11us/step - loss: 0.0891 - acc: 0.2706 - val_loss: 0.0889 - val_acc: 0.2715
Epoch 7/20
60000/60000 [==============================] - 1s 11us/step - loss: 0.0888 - acc: 0.2905 - val_loss: 0.0886 - val_acc

In [66]:
# we get better results as we increase the epoch number
# if you do not restar the kernel training goes on from the preboius one so you should restar kernel if you 
# change epoch

In [67]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0838 - acc: 0.3348 - val_loss: 0.0836 - val_acc: 0.3388
Epoch 2/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0835 - acc: 0.3372 - val_loss: 0.0832 - val_acc: 0.3420
Epoch 3/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0831 - acc: 0.3403 - val_loss: 0.0828 - val_acc: 0.3462
Epoch 4/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0827 - acc: 0.3439 - val_loss: 0.0824 - val_acc: 0.3512
Epoch 5/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0822 - acc: 0.3472 - val_loss: 0.0820 - val_acc: 0.3563
Epoch 6/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0818 - acc: 0.3510 - val_loss: 0.0816 - val_acc: 0.3622
Epoch 7/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0814 - acc: 0.3566 - val_loss: 0.0811 - 

60000/60000 [==============================] - 1s 13us/step - loss: 0.0576 - acc: 0.6549 - val_loss: 0.0569 - val_acc: 0.6555
Epoch 60/200
60000/60000 [==============================] - 1s 14us/step - loss: 0.0571 - acc: 0.6573 - val_loss: 0.0564 - val_acc: 0.6583
Epoch 61/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0567 - acc: 0.6597 - val_loss: 0.0560 - val_acc: 0.6604
Epoch 62/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0563 - acc: 0.6624 - val_loss: 0.0556 - val_acc: 0.6645
Epoch 63/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0559 - acc: 0.6658 - val_loss: 0.0551 - val_acc: 0.6677
Epoch 64/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0555 - acc: 0.6681 - val_loss: 0.0547 - val_acc: 0.6703
Epoch 65/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0550 - acc: 0.6711 - val_loss: 0.0543 - val_acc: 0.6742
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0383 - acc: 0.8007 - val_loss: 0.0373 - val_acc: 0.8103
Epoch 119/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0380 - acc: 0.8026 - val_loss: 0.0371 - val_acc: 0.8117
Epoch 120/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0378 - acc: 0.8043 - val_loss: 0.0369 - val_acc: 0.8132
Epoch 121/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0376 - acc: 0.8063 - val_loss: 0.0366 - val_acc: 0.8143
Epoch 122/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0374 - acc: 0.8081 - val_loss: 0.0364 - val_acc: 0.8166
Epoch 123/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0371 - acc: 0.8095 - val_loss: 0.0362 - val_acc: 0.8189
Epoch 124/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0369 - acc: 0.8113 - val_loss: 0.0360 - val_acc: 0.8196
Epoch 125/200
60000/

60000/60000 [==============================] - 1s 11us/step - loss: 0.0286 - acc: 0.8569 - val_loss: 0.0276 - val_acc: 0.8638
Epoch 177/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0285 - acc: 0.8574 - val_loss: 0.0275 - val_acc: 0.8641
Epoch 178/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0284 - acc: 0.8578 - val_loss: 0.0274 - val_acc: 0.8646
Epoch 179/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0283 - acc: 0.8583 - val_loss: 0.0273 - val_acc: 0.8656
Epoch 180/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0282 - acc: 0.8588 - val_loss: 0.0272 - val_acc: 0.8659
Epoch 181/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0281 - acc: 0.8592 - val_loss: 0.0271 - val_acc: 0.8663
Epoch 182/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0280 - acc: 0.8595 - val_loss: 0.0270 - val_acc: 0.8669
Epoch 183/200
60000/60000 [=======